---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/fig_rot_profiles/mesa+gyre.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/14366/articles/278183/master/folder/figures/fig_rot_profiles"
    url: "/users/14366/articles/278183/master/file/figures/fig_rot_profiles/mesa+gyre.svg"
